version: "3.3"
services:
  backend:
    build: .
    tty: true
    container_name: "backend"
    volumes:
      - ".:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    privileged: true
    runtime: nvidia
    environment:
      - OMPI_ALLOW_RUN_AS_ROOT=1
      - OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    image: 'detectme'
    ipc: 'host'
    stdin_open: true
  modeler:
    build: "../Plato3D/deploy"
    container_name: "deployed_modeler_2"
    ports:
      - "8080:80"
  mongo:
    image: mongo
    ports:
      - "27017:27017"

